In [4]:
import json
import pandas as pd
import os
import duckdb
folder_path = "json_files/"

In [5]:
def empty_json():
    for item in os.listdir(folder_path):
        # Get the full path of the item
        full_path = os.path.join(folder_path, item)
        if full_path != 'json_files/key_info.json':
            empty = []
            with open(full_path, 'w') as file:
                json.dump(empty, file, indent=4)
            print('overwritten ', full_path)
        else:
            reset_key = [{
                            "last_pk": 0
                        }]
            with open(full_path, 'w') as file:
                json.dump(reset_key, file, indent=4)
            print('key reset')

In [25]:
empty_json()

overwritten  json_files/ISF.json
key reset
overwritten  json_files/location.json
overwritten  json_files/media.json
overwritten  json_files/personnel.json
overwritten  json_files/site_activity.json
overwritten  json_files/subsystem.json
overwritten  json_files/systembaseline.json
overwritten  json_files/test.json

In [17]:
with open(folder_path + 'systembaseline.json', 'r') as file:
    systembaseline_list = json.load(file)

In [18]:
with open(folder_path + 'site_activity.json', 'r') as file:
    site_activity_list = json.load(file)

In [19]:
systembaseline_list

[{'FK': 1, 'systembaseline': '4.7.3.2'}]

In [20]:
site_activity_list

[{'Timestamp': '2026-10-13T16:45:16.624Z',
  'Date of Site Activity': '2026-10-14',
  'Start Time': '08:00',
  'End Time': '18:00',
  'Activity Description': 'Testing',
  'Send': 1,
  'PK': 1}]

In [21]:
df_site_activity = pd.DataFrame(site_activity_list)

In [22]:
df_site_activity

,Timestamp,Date of Site Activity,Start Time,End Time,Activity Description,Send,PK
0,2026-10-13T16:45:16.624Z,2026-10-14,08:00,18:00,Testing,1,1

In [23]:
new_columns = [df_site_activity.columns[-1]] + list(df_site_activity.columns[:-1])
df_site_activity = df_site_activity[new_columns]

In [24]:
df_site_activity

,PK,Timestamp,Date of Site Activity,Start Time,End Time,Activity Description,Send
0,1,2026-10-13T16:45:16.624Z,2026-10-14,08:00,18:00,Testing,1

In [50]:
all_df = {}

for item in os.listdir(folder_path):
        # Get the full path of the item
    full_path = os.path.join(folder_path, item)
    print(full_path)
    with open(full_path, 'r') as file:
        new_table = json.load(file)
    idx = item.index('.')
    all_df[item[:idx]] = pd.DataFrame(new_table)
    all_df[item[:idx]].columns = all_df[item[:idx]].columns.str.replace(" ", "_")

all_df.keys()

json_files/ISF.json
json_files/key_info.json
json_files/location.json
json_files/media.json
json_files/personnel.json
json_files/site_activity.json
json_files/subsystem.json
json_files/systembaseline.json
json_files/test.json

dict_keys(['ISF', 'key_info', 'location', 'media', 'personnel', 'site_activity', 'subsystem', 'systembaseline', 'test'])

In [51]:
locals().update(all_df)

In [62]:
query = """
SELECT media, Date_of_Site_Activity
FROM site_activity
JOIN media
ON site_activity.PK = media.FK
"""
result_df = duckdb.query(query).to_df()
result_df

                                               media Date_of_Site_Activity
0  https://drive.google.com/open?id=1gSc1Kw7H6slI...            2026-10-14
1  https://drive.google.com/open?id=1uM6nE2A8g0Pv...            2026-10-14